### ISSUE TITLE
Minecraft server fails to install because jq is missing in docker image

### ISSUE THREAD

**Issue by MiniMeOSc** [GameServerManagers/docker-gameserver#116]
When trying to set up a docker container with the following `docker-compose.yml` file the server will not come up.
```
services:
  linuxgsm-mc:
    image: gameservermanagers/gameserver:mc
    container_name: mcserver
    volumes:
      - ./mc:/data
    ports:
      - "25565:25565/tcp" # Game
      - "25565:25565/udp" # Query
      - "25575:25575/tcp" # RCON
    restart: unless-stopped
```
Looking at the logs I see that it doesn't start the server because the jar-file is missing:
```
INFO: LinuxGSM version: v25.1.1
Feb 09 13:50:27.749 mcserver: UPDATE: PASS: core_exit.sh exiting with code: 0
Feb 09 13:50:28.762 mcserver: START: FAIL: Executable was not found: /data/serverfiles/minecraft_server.jar
Feb 09 13:50:28.769 mcserver: START: INFO: LinuxGSM version: v25.1.1
Feb 09 13:50:28.770 mcserver: START: FAIL: core_exit.sh exiting with code: 1
```
Looking at the section in the logs where it'd update and download the jar-file I can see that this fails because `jq` is missing
```
[ .... ] Updating mcserver: 
Installing Gamedig
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   746  100   746    0     0  16010      0 --:--:-- --:--:-- --:--:-- 16217
npm warn deprecated event-to-promise@0.7.0: Use promise-toolbox/fromEvent instead
added 68 packages, and audited 69 packages in 3s
27 packages are looking for funding
  run `npm fund` for details
found 0 vulnerabilities

[ FAIL ] Updating mcserver: jq is not installed
/app/lgsm/modules/update_mc.sh: line 172: fn_script_log_fatal: command not found
```

Maybe this can be fixed by adding an additional dependency `jq` to [ubuntu-24.04.csv:68](https://github.com/GameServerManagers/LinuxGSM/blob/5eeb9b55ea969a3b6c3485079d37ee7b34ad2183/lgsm/data/ubuntu-24.04.csv#L68)?

Find the full log file for reference here: [_mcserver_logs.txt](https://github.com/user-attachments/files/18724879/_mcserver_logs.txt)
