### ISSUE TITLE
question for linuxgsm/root user, and custom crontab

### ISSUE THREAD

**Issue by Lxeon** [GameServerManagers/docker-gameserver#39]
hello everyone,

i try to use custom crontab in linuxgsm user, and i find out it will restore to default if i restart container, and even before restart container, the crontab will not work as expected, like no run the command
here is the crontab
```
*/60 * * * * /app/mcserver update > /dev/null 2>&1
0 * * * * /app/mcserver send "kill @e[type=item]"
```

and then i try to set up crontab in root user like this
```
0 * * * * su - linuxgsm -c '/app/mcserver send "kill @e[type=item]"'
```
it can't run either.

when i run command alone, its show "server not running".

then i type
> su - linuxgsm -c '/app/mcserver dt'

![图片](https://github.com/GameServerManagers/docker-gameserver/assets/28784869/6a306457-a5e8-4dab-95ef-1be295d11569)

seems its wrong config file path. maybe its environment problem? but i check the 'env' in linuxgsm user and root user, its the same.

here is my docker-compose
```
  minecraft:
    image:  gameservermanagers/gameserver:mc
    container_name: minecraft
    volumes:
      - /mnt/ssd/docker/minecraft:/data
    network_mode: host
    restart: always
```

any idea for it ?
