### ISSUE TITLE
Setting UID/GID/USER is broken

### ISSUE THREAD

**Issue by noillt** [GameServerManagers/docker-gameserver#76]
We had an issue where the docker image `gameservermanagers/gameserver:css` was setting `UID` and `GID` to `1000` which was the wrong user on our server. 

After noticing that it's set through ENV we added variable overrides to `docker-compose.yml` *(some data is redacted)*:
```yml
version: "3.8"
services:
  linuxgsm-css-bind:
    image: gameservermanagers/gameserver:css
    environment:
      - USER=combat
      - UID=1005
      - GID=1005
```
But the docker image would still fail with:
```
combat-css-server  | Switch to user combat
combat-css-server  | =================================
combat-css-server  | error: failed switching to "combat": unable to find user combat: no matching entries in passwd file
combat-css-server  | 
combat-css-server  | Check Permissions
combat-css-server  | =================================
combat-css-server  | setting UID to 1005
combat-css-server  | setting GID to 1005
combat-css-server  | updating permissions for /data
combat-css-server  | chown: invalid user: ‘combat:combat’
combat-css-server  | updating permissions for /app
combat-css-server  | chown: invalid user: ‘combat:combat’
```

The problem is that the user exists
```sh
# combat@noil:~$ id
uid=1005(combat) gid=1005(combat) groups=1005(combat),100(users),994(docker)
```

**Comment by successtheman** [comment]
I tried to make a user with the same UID and GID as the ones it was chowning the files to and then added my user to that group. Unfortunately when it detected that the user existed it would then make it another one, I believe this is similar to what you are saying? I wish there was a flag to just make it run as root because honestly I just start it when I want to play l4d2 so I don't really care about how secure it is or not

**Comment by WildPenquin** [comment]
Maybe I'm a bit lost here, but I'm confused what you've done outside and what you've done inside the container. 

Care to elaborate, why do you need another user besides linuxgsm? Why isn't the linuxgsm user enough? Where/how have you exactly determined, it is setting the wrong UID/GID? When running inside the container, or are you trying to access the files outside the container (on the host)?

It seems like you have created a user "combat" inside the container, want to run the container as user "combat", and expect the UIDs and GIDs to match?

Please note that the idea of a container is that it has a totally different namespace. The whole point is that the UIDs, GIDs don't match with anything on the host. The user accounts are separate.

Bind mounts have nothing to do with UID nor GID management, really.

Or, sorry if I'm misinterpreting totally what you have done and asking help for =).

**Comment by successtheman** [comment]
> Maybe I'm a bit lost here, but I'm confused what you've done outside and what you've done inside the container.
> 
> Care to elaborate, why do you need another user besides linuxgsm? Why isn't the linuxgsm user enough? Where/how have you exactly determined, it is setting the wrong UID/GID? When running inside the container, or are you trying to access the files outside the container (on the host)?
> 
> It seems like you have created a user "combat" inside the container, want to run the container as user "combat", and expect the UIDs and GIDs to match?
> 
> Please note that the idea of a container is that it has a totally different namespace. The whole point is that the UIDs, GIDs don't match with anything on the host. The user accounts are separate.
> 
> Bind mounts have nothing to do with UID nor GID management, really.
> 
> Or, sorry if I'm misinterpreting totally what you have done and asking help for =).

As I said I tried to set the UID and GID to the same thing the container was chowning the mounted folders to. It's nice that linuxgsm thinks it needs to chown all mounted files/folders every time the container starts (which is completely unnecessary but it still does it). Thing is I need to be able to edit the files that are mounted or I can't set up the server, call me crazy. None of the https://www.linuxserver.io/ images have this issue and they allow the user to run the image with whatever permissions they want for the mounted files/folders. For some reason all L4D2/srcds images think they need to chown everything. In fact I run most docker containers with root UID/GID 0 to avoid permission issues so that the container can access the mounted files without issues (spare me the speech about this being a bad idea I do it anyway), but this image thinks it needs to chmod my files every time to some random user no matter which UID/GID I specify. 

Because of all this I gave up running srcds servers with docker images and on Linux as a whole and moved to Windows server within proxmox where I don't have to deal with this. Wish the others best of luck though. Maybe some day the container will not chown every file when it isn't necessary, who knows.

**Comment by successtheman** [comment]
> I am also having the same issue, I can't actually create a backup of Palworld server because the user doesn't have permissions to create directories in the host directory.
> 
> the issue seems to stem from the linuxgsm userid of 1000 and the default/first user created on the host gets userid 1000.
> 
> what is the best of changing this to prevent issues moving forward?

Not running it in a docker container and just running it on system is the only real option I can see, but I opted to run my server on windows on system instead of linux

**Comment by saedrin** [comment]
This is very frustrating for me as well. I run a ton of containers on this host and this container essentially requiring UID 1000 is making a mess. I'm not sure what the solution is, but maybe something like a config check it can reference on start to switch the UID/GID would be very welcome.

**Comment by Arcitec** [comment]
Oh and somebody mentioned using Podman.

You cannot use podman as-is. You need to add this too:

```yaml
    security_opt:
      - label=disable
```

Otherwise your container will not have permission to access the mounted files and you will see errors like `chown: cannot read directory '/data': Permission denied`.

Here's an example of a working container `compose.yml` for 7 Days to Die running via `podman up`:

```yaml
name: server-7days

services:
  linuxgsm:
    image: ghcr.io/gameservermanagers/gameserver:sdtd

    # Force a specific container name to easily control it later.
    container_name: sdtdserver

    # Disable SELinux to avoid having to deal with permission labels.
    security_opt:
      - label=disable

    # Persistent server data directory.
    volumes:
      - ./data:/data

    environment:
      # Use the same UID/GID as the host user, to easily mount files.
      - UID=1000
      - GID=1000

    # External ports.
    ports:
      # https://7dtd.illy.bz/wiki/Ports
      - "26900:26900/tcp"                # Game (Game details query port)
      - "26900-26902:26900-26902/udp"    # Game (0: Steam's master server list interface, 1: Steam communication, 2: networking via LiteNetLib)
      - "127.0.0.1:26903:8080/tcp"       # Web based control panel (localhost only)
      - "127.0.0.1:26904:8081/tcp"       # Telnet control interface (localhost only)

    # Automatically restart if the server process crashes.
    restart: unless-stopped
```
